name: flutter_protector
description: A Flutter plugin that provides device and platform-related security features. # Improve the description
version: 0.4.3 # Use semantic versioning (major.minor.patch+build_number)
homepage: https://github.com/PuzzleTakX/flutter_protector # Add your repo URL
repository: https://github.com/PuzzleTakX/flutter_protector
issue_tracker: https://github.com/PuzzleTakX/flutter_protector/issues # Optional: Link to your issue tracker
documentation: https://github.com/PuzzleTakX/flutter_protector/blob/master/README.md # Optional: Link to documentation
license: MIT # Add a license
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: The flutter protector package logo.
    path: screenshots/logo.png

flutter:
  plugin:
    platforms:
      android:
        package: com.puzzletak.flutter_protector # Update with your package name
        pluginClass: FlutterProtectorPlugin # Update with your plugin class name
#      web:
#        pluginClass: FlutterProtectorWeb
#        fileName: flutter_protector_web.dart